import type { User, Tool, Log } from './types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Alex Johnson',
    email: 'alex@example.com',
    avatarUrl: 'https://avatar.vercel.sh/alex@example.com.png',
    department: 'Dev',
    role: 'super_admin',
    assignedTools: ['tool-1', 'tool-2', 'tool-3', 'tool-4', 'tool-5'],
  },
  {
    id: 'user-2',
    name: 'Maria Garcia',
    email: 'maria@example.com',
    avatarUrl: 'https://avatar.vercel.sh/maria@example.com.png',
    department: 'Marketing',
    role: 'employee',
    assignedTools: ['tool-4'],
  },
  {
    id: 'user-3',
    name: 'David Smith',
    email: 'david@example.com',
    avatarUrl: 'https://avatar.vercel.sh/david@example.com.png',
    department: 'Sales',
    role: 'employee',
    assignedTools: [],
  },
  {
    id: 'user-4',
    name: 'Sarah Lee',
    email: 'sarah@example.com',
    avatarUrl: 'https://avatar.vercel.sh/sarah@example.com.png',
    department: 'Marketing',
    role: 'department_admin',
    assignedTools: ['tool-1', 'tool-4', 'tool-5'],
  },
    {
    id: 'user-5',
    name: 'Tom Brown',
    email: 'tom@example.com',
    avatarUrl: 'https://avatar.vercel.sh/tom@example.com.png',
    department: 'Unassigned',
    role: 'management',
    assignedTools: [],
  },
  {
    id: 'user-6',
    name: 'Dev Employee',
    email: 'dev.employee@example.com',
    avatarUrl: 'https://avatar.vercel.sh/dev.employee@example.com.png',
    department: 'Dev',
    role: 'employee',
    assignedTools: [],
  },
  {
    id: 'user-7',
    name: 'HR Admin',
    email: 'hr.admin@example.com',
    avatarUrl: 'https://avatar.vercel.sh/hr.admin@example.com.png',
    department: 'HR',
    role: 'department_admin',
    assignedTools: [],
  },
];

export const mockTools: Tool[] = [
  {
    id: 'tool-1',
    name: 'ChatGPT',
    iconUrl: 'https://placehold.co/100x100/815FAD/FFFFFF.png?text=GPT',
    launchUrl: 'https://chat.openai.com/',
    description: 'A powerful language model for conversation, content creation, and more.',
    type: 'Web-based',
    category: 'Web-based',
    status: 'active',
    assignedDepartments: ['Dev', 'Marketing'],
    assignedUsers: ['user-1'],
  },
  {
    id: 'tool-2',
    name: 'Fireflies.ai',
    iconUrl: 'https://placehold.co/100x100/815FAD/FFFFFF.png?text=FF',
    launchUrl: 'https://fireflies.ai/',
    description: 'AI assistant for your meetings. Records, transcribes, and analyzes voice conversations.',
    type: 'Web-based',
    category: 'Web-based',
    status: 'active',
    assignedDepartments: ['Sales'],
    assignedUsers: ['user-1'],
  },
  {
    id: 'tool-3',
    name: 'Content Assistant',
    iconUrl: 'https://placehold.co/100x100/815FAD/FFFFFF.png?text=CA',
    launchUrl: '',
    description: 'AI features integrated into the workspace for writing, summarizing, and brainstorming with documents and images.',
    type: 'API-integrated',
    category: 'Text',
    status: 'active',
    assignedDepartments: ['Dev'],
    assignedUsers: ['user-1'],
  },
  {
    id: 'tool-4',
    name: 'Midjourney',
    iconUrl: 'https://placehold.co/100x100/815FAD/FFFFFF.png?text=MJ',
    launchUrl: 'https://www.midjourney.com/',
    description: 'An independent research lab exploring new mediums of thought and expanding the imaginative powers of the human species.',
    type: 'Web-based',
    category: 'Web-based',
    status: 'inactive',
    assignedDepartments: [],
    assignedUsers: ['user-1', 'user-2', 'user-4'],
  },
  {
    id: 'tool-5',
    name: 'Image Generator',
    iconUrl: 'https://placehold.co/100x100/815FAD/FFFFFF.png?text=IMG',
    launchUrl: '',
    description: 'Generate high-quality images from text descriptions using a powerful AI model.',
    type: 'API-integrated',
    category: 'Image',
    status: 'active',
    assignedDepartments: ['Marketing'],
    assignedUsers: ['user-1', 'user-4'],
  },
];

export const mockLogs: Log[] = [
  {
    id: 'log-1',
    toolId: 'tool-1',
    toolName: 'ChatGPT',
    userId: 'user-2',
    userName: 'Maria Garcia',
    department: 'Marketing',
    timestamp: new Date('2023-10-26T10:00:00Z'),
  },
  {
    id: 'log-2',
    toolId: 'tool-2',
    toolName: 'Fireflies.ai',
    userId: 'user-3',
    userName: 'David Smith',
    department: 'Sales',
    timestamp: new Date('2023-10-26T11:30:00Z'),
  },
  {
    id: 'log-3',
    toolId: 'tool-1',
    toolName: 'ChatGPT',
    userId: 'user-1',
    userName: 'Alex Johnson',
    department: 'Dev',
    timestamp: new Date('2023-10-27T14:00:00Z'),
  },
    {
    id: 'log-4',
    toolId: 'tool-4',
    toolName: 'Midjourney',
    userId: 'user-4',
    userName: 'Sarah Lee',
    department: 'Marketing',
    timestamp: new Date('2023-10-28T14:00:00Z'),
  },
];
